// Ⅴの 決まった 検査。ブラウザ（headless Chrome）で index.html を 動かして 確かめる
//   用意：npm i puppeteer-core @sparticuz/chromium ／ three.min.js（r128）を index と 同じ 場所に 置いた 試し用の 場所を 用意して、
//   node test/run.js http://localhost:8772/index.html
const chromium=(m=>m.default||m)(require('@sparticuz/chromium')), pu=require('puppeteer-core');
const URL=process.argv[2]||'http://localhost:8772/index.html';
const W=ms=>new Promise(r=>setTimeout(r,ms));
let n=0, ng=0; const T=(name,ok,d)=>{ n++; if(!ok){ ng++; console.log('NG',name,d===undefined?'':d); } };
(async()=>{
  const b=await pu.launch({executablePath:await chromium.executablePath(), args:chromium.args, headless:true});
  const pg=await b.newPage(); await pg.setViewport({width:393,height:852});
  const errs=[]; pg.on('pageerror',e=>errs.push(e.message));
  await pg.goto(URL,{waitUntil:'load'}); await pg.evaluate(()=>localStorage.clear()); await pg.reload({waitUntil:'load'}); await W(1500);
  const E=(f,a)=>pg.evaluate(f,a);
  const flush=async()=>{ for(let i=0;i<60;i++){ if(!(await E(()=>!!msgQ))) break; await E(()=>pressA()); await W(30);} };
  const talk=async(re)=>{ await E((re)=>{ const x=cur.npcs.find(n=>new RegExp(re).test(n.name)); if(!x) return; const bl=linesByPhase(x); if(bl) say(bl); else if(x.talk) x.talk(x); else say(x.lines); },re); await W(60); };
  const waitMenu=async()=>{ for(let i=0;i<80;i++){ await W(100); if(await E(()=>BT&&BT.phase==='menu')) return true; } return false; };
  const winBattle=async()=>{ await waitMenu(); await E(()=>{ BT.foes.forEach(f=>f.hp=1); for(let k=0;k<12 && BT && BT.phase!=='act';k++){ if(BT.phase==='menu') BT.sel=0; pressA(); } }); for(let i=0;i<120;i++){ await W(100); if(await E(()=>!BT)) break; } await W(200); };
  const pick=async(l)=>{ await E((l)=>{ const i=MENU.items.findIndex(t=>t.indexOf(l)>=0); MENU.sel=i; pressA(); },l); await W(60); };
  await flush();
  // ---- 序章 ----
  T('はじめは 朝の 村', await E(()=>ST.phase==='morning'&&cur.kind==='town'));
  T('はじめの 位置で 動ける', await E(()=>freeCircle(hero.x,hero.z)));
  await talk('ガイル'); await flush(); T('ガイルで 見回りへ', await E(()=>ST.phase==='field'));
  await E(()=>enterFarm()); await E(()=>{ hero.x=19; hero.z=8.5; hero.ang=Math.PI; pressA(); }); await flush(); T('倉で 警鐘', await E(()=>ST.phase==='raid'));
  await E(()=>{ enterTown([12,1.2]); startRaid(); }); await flush(); T('村が 燃える', await E(()=>ST.phase==='burn'));
  for(const x of ['娘','老人','子']){ await talk('逃げ遅れた '+x); await flush(); }
  T('3人 助ける', await E(()=>Object.keys(ST.rescued).length===3));
  await talk('部隊長'); await flush(); T('部隊長戦の 背景は 燃える村', await waitMenu() && await E(()=>BT.look==='burn'));
  await winBattle(); await flush(); T('部隊長の 後', await E(()=>ST.phase==='after'));
  await talk('ガイル'); await flush(); T('ガイルの 剣', await E(()=>ST.phase==='road'&&EQUIP.elt.weapon.name==='ガイルの 剣'));
  await E(()=>enterTown([12,20.2],'cap')); T('夜に 王都の 城下町', await E(()=>TOWN_NOW==='cap'));
  await E(()=>enterCastle()); await talk('アルディア王'); await flush(); await W(300); T('序章 完', await E(()=>ST.phase==='end'));
  // ---- 第1章 ----
  await E(()=>pressA()); await W(400); await flush(); T('第1章へ', await E(()=>ST.phase==='c1_castle'));
  await talk('アルディア王'); await flush(); T('使者と 書状', await E(()=>ST.phase==='c1_road'&&followers.length===1&&BAG.keys.includes('和平の 書状の 写し')));
  await E(()=>enterFort(false)); await W(800); await flush(); T('砦の 入口で 重ならない', await E(()=>freeCircle(hero.x,hero.z)));
  T('鉄格子は 閉じて いる', await E(()=>!fortGateOpen()));
  for(const [x,z] of [[1.5,9.5],[5.5,1.5]]){ await E(([x,z])=>{ hero.x=x; hero.z=z; examine(); },[x,z]); await flush(); }
  T('灯り ふたつで 鉄格子が 開く', await E(()=>fortGateOpen()));
  await talk('番兵'); await flush(); await winBattle(); await flush(); T('番兵の 後', await E(()=>ST.phase==='c1_east'));
  await E(()=>{ ST.phase='c1_town'; enterTown([11.5,18.2],'velna'); }); await talk('古い 兵'); await flush(); await talk('町の 長'); await flush(); await W(300); T('第1章 完', await E(()=>ST.phase==='c1_end'));
  // ---- 仕組み ----
  await E(()=>{ ST.phase='c1_road'; enterTown([12,10],'cap'); });
  await E(()=>{ BAG.gold=500; openShop('smith','店'); }); await pick('買う'); await pick('鉄の 兜'); await flush(); await E(()=>closeMenu());
  await E(()=>openEquip()); await pick('頭'); await pick('鉄の 兜'); await flush(); await E(()=>closeMenu());
  T('兜を 装備', await E(()=>EQUIP.elt.helm&&EQUIP.elt.helm.name==='鉄の 兜'));
  const g0=await E(()=>BAG.gold); await E(()=>{ TOWN_NOW='velna'; openTrade(); }); await pick('鉄鉱石'); await pick('買う'); await E(()=>{ closeMenu(); TOWN_NOW='cap'; openTrade(); }); await pick('鉄鉱石'); await pick('売る'); await E(()=>closeMenu());
  T('交易で もうかる（ドルムで 買い 王都で 売る）', await E((g0)=>BAG.gold>g0,g0));
  await talk('王都の 男'); await flush(); T('頼みごとを 受ける', await E(()=>ST.q.wara==='受けた'));
  for(let i=0;i<3;i++){ await E(()=>{ enterWorld([22.5,31.5]); startBattle([FOES.waradokuro]); }); await winBattle(); }
  await E(()=>enterTown([12,10],'cap')); await talk('王都の 男'); await flush(); T('頼みごとの お礼', await E(()=>ST.q.wara==='済み'));
  await E(()=>{ STATS.elt.lv=5; STATS.elt.mp=20; enterWorld([22.5,31.5]); startBattle([FOES.nousagi]); }); await waitMenu();
  await E(()=>{ BT.sel=CMDS.indexOf('呪文'); pressA(); }); T('呪文の 一覧', await E(()=>BT.phase==='skill'&&BT.sks.some(k=>k.name==='ブレイズエッジ')));
  await E(()=>{ BT.ssel=BT.sks.findIndex(k=>k.name==='ブレイズエッジ'); pressA(); }); for(let i=0;i<40;i++){ await W(100); if(await E(()=>BT&&BT.phase==='menu')||await E(()=>!BT)) break; }
  T('ブレイズエッジで MPが 減る', await E(()=>STATS.elt.mp===17));
  await E(()=>{ if(BT) endBattle(); STATS.elt.status=null; inflictOn(STATS.elt,'poison'); BAG.antidote=1; }); T('毒に なる', await E(()=>STATS.elt.status==='poison'));
  await E(()=>say(useAntidote(STATS.elt))); await flush(); T('どくけし草で 治る', await E(()=>!STATS.elt.status));
  T('作戦：いのちだいじに で 回復を 選ぶ', await E(()=>{ STATS.lidia={name:'リディア',lv:5,hp:5,max:30,mp:20,atk:6,defT:3}; PARTY.push('lidia'); startBattle([FOES.nousagi]); tactic='inochi'; const a=autoAct(BT.party[1]); endBattle(); PARTY.length=1; return a.kind==='skill'&&a.sk.type==='heal'; }));
  T('入れ替え（控え）', await E(()=>{ RESERVE.push('lidia'); const ok=openFieldMenu()===undefined && MENU.items.includes('入れ替え'); closeMenu(); RESERVE.length=0; return ok; }));
  T('船：海を 渡れる', await E(()=>{ enterWorld([22.5,31.5]); const a=blockedAt(1.5,1.5); ST.ship=1; const bb=blockedAt(1.5,1.5); ST.ship=0; return a&&!bb; }));
  T('戦闘の 速さ', await E(()=>{ SND.speed=2; const ok=SND.speed===2; SND.speed=1; return ok; }));
  T('章ごとの 台詞', await E(()=>{ enterTown([12,6],'cap'); const g=cur.npcs.find(x=>x.name==='城の 門番'); ST.phase='road'; const a=linesByPhase(g)[0]; ST.phase='c1_road'; const bb=linesByPhase(g)[0]; return a!==bb; }));
  T('2体まで（1人）', await E(()=>{ const sb=window.startBattle; let mx=0; window.startBattle=(d)=>{ mx=Math.max(mx,d.length); }; for(let i=0;i<500;i++) startEnc('west'); window.startBattle=sb; return mx===2; }));
  T('全滅すると 町へ', await (async()=>{ await E(()=>{ STATS.elt.hp=1; STATS.elt.defT=0; BAG.gold=100; enterWorld([22.5,31.5]); startBattle([FOES.ishikurage]); }); await waitMenu(); await E(()=>{ BT.sel=CMDS.indexOf('ぼうぎょ'); pressA(); }); for(let i=0;i<120;i++){ await W(100); if(await E(()=>!BT)) break; } await W(800); return E(()=>cur.kind==='town'&&BAG.gold===50&&STATS.elt.hp===STATS.elt.max); })());
  T('攻撃の 呪文は 3段階', await E(()=>{ const fam=[['tsuyogiri','blaze2','blaze3'],['volt','voltra','voltrion'],['hono','flare2','flare3'],['raigeki','thunder2','thunder3']]; return fam.every(f=>f.every(id=>SKILLS[id])); }));
  T('Lv28で ブレイズカリバーまで 覚える', await E(()=>{ const lv=STATS.elt.lv; STATS.elt.lv=28; const n=skillsOf('elt').map(k=>k.name); STATS.elt.lv=lv; return ['ブレイズエッジ','ブレイズセイバー','ブレイズカリバー','ヴォルト','ヴォルトラ'].every(x=>n.includes(x)) && !n.includes('ヴォルトリオン'); }));
  T('ヴォルトリオンは 物語で 授かる', await E(()=>{ STATS.elt.extra=['voltrion']; const ok=skillsOf('elt').some(k=>k.name==='ヴォルトリオン'); STATS.elt.extra=[]; return ok; }));
  T('ドルガンの 技（兜割り・大魔神斬り・ダブルファングは Lv28）', await E(()=>{ STATS.dolgan={name:'ドルガン',lv:27,hp:60,max:60,mp:10,atk:20,defT:8}; const a=skillsOf('dolgan').map(k=>k.name); STATS.dolgan.lv=28; const b=skillsOf('dolgan').map(k=>k.name); return a.includes('兜割り')&&a.includes('大魔神斬り')&&!a.includes('ダブルファング')&&b.includes('ダブルファング'); }));
  T('大魔神斬り：はずれ／当たれば 会心', await E(()=>{ PARTY.push('dolgan'); startBattle([FOES.banpei]); const m=BT.party[1], f=BT.foes[0]; const r=Math.random; Math.random=()=>.9; actOf(m,{kind:'skill',sk:Object.assign({id:'daimajin'},SKILLS.daimajin),target:f})(); const miss=f.hp===f.max; Math.random=()=>.1; actOf(m,{kind:'skill',sk:Object.assign({id:'daimajin'},SKILLS.daimajin),target:f})(); const hit=f.max-f.hp; Math.random=r; endBattle(); PARTY.length=1; return miss && hit===Math.min(f.max,Math.round((20+3)*2.4)); }));
  T('火炎斬り：通常の 攻撃の 1.3倍', await E(()=>{ PARTY.push('dolgan'); STATS.dolgan.mp=10; startBattle([FOES.banpei]); const m=BT.party[1], f=BT.foes[0]; const r=Math.random; Math.random=()=>.5; BT.steps=[]; actOf(m,{kind:'skill',sk:Object.assign({id:'kaenkiri'},SKILLS.kaenkiri),target:f})(); BT.steps.shift()(); const d=f.max-f.hp; Math.random=r; endBattle(); PARTY.length=1; return d===Math.round((20+Math.floor(.5*4))*1.3) && STATS.dolgan.mp===8; }));
  T('戦闘が 終わると 状態異常は 治る（毒も）', await (async()=>{ await E(()=>{ STATS.elt.hp=STATS.elt.max=999; enterWorld([22.5,31.5]); startBattle([FOES.nousagi]); }); await waitMenu(); await E(()=>{ inflictOn(BT.party[0],'poison'); }); await winBattle(); return E(()=>!STATS.elt.status); })());
  T('セーブして 再開しても 村は 燃えた まま（ガイルの 別れの 後）', await (async()=>{ await E(()=>{ ST.phase='road'; enterTown([12,10],'rue'); saveGame(); }); await pg.reload({waitUntil:'load'}); for(let i=0;i<60;i++){ await W(150); if(await E(()=>typeof MENU!=='undefined' && !!MENU)) break; } await E(()=>{ MENU.sel=0; pressA(); }); await W(1000); return E(()=>ST.phase==='road' && TOWN_NOW==='rue' && fireMeshes.length>0 && S.background.getHex()===0x1a0f18); })());
  T('北から 村の 印に 入れる', await (async()=>{ await flush(); await E(()=>{ ST.phase='c1_road'; enterWorld([34.5,29.6]); }); await W(1500); await flush(); await pg.keyboard.down('ArrowDown'); for(let i=0;i<100;i++){ await W(120); if(await E(()=>cur.kind==='town')) break; } await pg.keyboard.up('ArrowDown'); await W(500); return E(()=>cur.kind==='town'&&TOWN_NOW==='rue'); })());
  T('夜の 街道の 戦闘は 戦闘の 曲（燃える 村の 曲では ない）', await E(()=>{ TOWN_NOW='rue'; ST.phase='road'; enterWorld([30.5,25.5]); startBattle([FOES.yomiakari]); const k=bgmFor(); endBattle(); enterTown([12,10],'rue'); const k2=bgmFor(); return k==='battle' && k2==='burn'; }));
  T('メニューで 仲間の 状態と 所持金', await E(()=>{ if(BT) endBattle(); enterTown([12,10],'cap'); BAG.gold=123; openFieldMenu(); const el=document.getElementById('fstat'); const ok=el.style.display==='block' && el.textContent.includes('エルト') && el.textContent.includes('123 G') && el.textContent.includes('HP'); closeMenu(); return ok && el.style.display==='none'; }));
  T('メニューの 頼まれごと', await E(()=>{ const l=requestList().join(' '); return /畑の ワラドクロ退治/.test(l) && /済み/.test(l); }));
  T('扉の 音は 1回だけ', await (async()=>{ await flush(); await E(()=>{ if(MENU) closeMenu(); if(BT) endBattle(); ST.phase='c1_road'; enterTown([12,10],'cap'); window.__door=0; const o=SE.door; SE.door=()=>{ window.__door++; }; window.__oDoor=o; const [dx,dy]=TDOORS()[0]; hero.x=dx+.5; hero.z=dy+.9; hero.ang=Math.PI; }); await pg.keyboard.down('ArrowUp'); await W(2200); await pg.keyboard.up('ArrowUp'); await W(600); const r=await E(()=>{ SE.door=window.__oDoor; return [window.__door,cur.kind,hero.x.toFixed(2),hero.z.toFixed(2),busyDoor,fading,!!msgQ,!!MENU].join(' '); }); return /^1 room/.test(r); })());
  T('戦闘の 背景の 空の 色が 切り替わる', await E(()=>{ ST.phase='road'; enterWorld([30.5,25.5]); startBattle([FOES.yomiakari]); const c=batScene.background.getHex(); endBattle(); return c===0x0a1028; }));
  // ---- 第2章 ----
  await E(()=>{ if(BT) endBattle(); PARTY.length=1; STATS.elt.hp=STATS.elt.max; ST.phase='c1_town'; setEscort(true); enterTown([11.5,15.5],'velna'); showEnd1(); });
  await E(()=>pressA()); await W(500); await flush(); T('第2章へ', await E(()=>ST.phase==='c2_dolm' && TOWN_NOW==='velna' && followers.length===1));
  await talk('迎えの 騎士'); await flush(); T('峠が 開く', await E(()=>ST.phase==='c2_pass' && WORLD[25][62]==='G'));
  await E(()=>enterWorld([60.5,25.5])); await W(800); await pg.keyboard.down('ArrowRight'); for(let i=0;i<30;i++){ await W(100); if(await E(()=>cur.kind==='dun')) break; } await pg.keyboard.up('ArrowRight'); await W(500);
  T('峠の 山道に 入る', await E(()=>cur.kind==='dun' && DUN_NOW==='pass' && freeCircle(hero.x,hero.z)));
  await talk('関所荒らし'); await flush(); await winBattle(); await flush(); T('中ボスの 後', await E(()=>ST.phase==='c2_road' && !cur.npcs.some(n=>n.foe)));
  await E(()=>{ ST.phase='c2_road'; enterTown([12,20.2],'vcap'); ST.phase='c2_capital'; enterCastle('velna'); }); await talk('ヴェルナ王'); await flush(); T('謁見で ハーヴェンが 外れる', await E(()=>ST.phase==='c2_inn' && followers.length===0));
  await E(()=>{ enterTown([12,10],'vcap'); lastDoor=3; enterRoom(3); }); await talk('宿の 娘'); await flush(); await E(()=>{ MENU.sel=0; pressA(); }); for(let i=0;i<40 && !(await E(()=>cur.kind==='tower'));i++){ await W(250); await flush(); } await W(400);
  T('宿で 夜の 塔へ', await E(()=>ST.phase==='c2_tower' && cur.kind==='tower'));
  await talk('リディア'); await flush(); await W(800); await flush(); T('リディアが 加わる', await E(()=>ST.phase==='c2_ruins' && PARTY.includes('lidia') && STATS.lidia.lv>=10));
  await E(()=>enterDun('ruins')); await W(900); await flush(); T('遺跡の 奥は 光の 壁で 閉じて いる', await E(()=>!ST.ruinsOpen && blockedAt(9.2,1.95) && !blockedAt(9.2,2.6)));
  await E(()=>{ hero.x=1.5; hero.z=2.5; examine(); }); await flush(); T('遺跡の 機械：順番を 間違えると 戻る', await E(()=>!(ST.ruinSeq||[]).length));
  for(const [x,z] of [[4.5,11.5],[1.5,2.5],[17.5,2.5],[14.5,11.5]]){ await E(([x,z])=>{ hero.x=x; hero.z=z; examine(); },[x,z]); await flush(); }
  T('遺跡の 機械を 正しい 順に 動かすと 光の 壁が 消える', await E(()=>ST.ruinsOpen===1));
  T('ダンジョンに 宝箱が ある', await E(()=>CHESTS.fort.length>=1 && CHESTS.dun_pass.length>=3 && CHESTS.dun_ruins.length>=4));
  await E(()=>{ hero.x=9.5; hero.z=2.6; resetTrail(); }); await talk('からくり'); await flush(); await winBattle(); await flush(); await W(300); await flush(); T('ZFが 加わる', await E(()=>ST.phase==='c2_back' && PARTY.includes('zf')));
  await E(()=>enterCastle('velna')); await talk('ヴェルナ王'); await flush(); await W(300); T('第2章 完', await E(()=>ST.phase==='c2_end'));
  T('仲間も 経験値を もらう', await E(()=>{ const a=STATS.lidia.exp; gainExp(5); return STATS.lidia.exp===a+5; }));
  T('レベルが 上がると HPと MPが 全回復', await E(()=>{ const m=STATS.elt; m.hp=1; m.mp=0; m.exp=0; gainExp(expNeed(m.lv)); return m.hp===m.max && m.mp===m.maxmp; }));
  T('砦の 灯りに 近づくと 知らせが 出る', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.lamps={}; ST.lampSeen={}; ST.phase='c1_fort'; enterFort(false); }); await W(900); await flush(); await E(()=>{ hero.x=2.5; hero.z=9.5; hero.ang=-Math.PI/2; resetTrail(); }); await pg.keyboard.down('ArrowLeft'); await W(400); await pg.keyboard.up('ArrowLeft'); await W(200); const ok=await E(()=>!!msgQ && /灯りの 台/.test(msgEl.textContent)); await flush(); await E(()=>pressA()); await W(100); await flush(); return ok && await E(()=>!!ST.lamps['0,9']); })());
  T('町の 人が 外へ 出ても 残らない（砦の 壁の 門番）', await (async()=>{ await flush(); return E(()=>{ if(BT) endBattle(); ST.phase='c1_road'; enterTown([12,20.2],'cap'); const ms=cur.npcs.map(n=>n.p.m); enterWorld([12.5,25.45]); enterFort(false); return ms.length>0 && ms.every(m=>!S.children.includes(m)); }); })());
  T('戦闘で ダメージの 数字が 出る（Ⅳと 同じ）', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); startBattle([FOES.nousagi]); }); await W(1500); await E(()=>{ BT.foes[0].hp-=5; }); await W(120);
    const ok=await E(()=>[...document.querySelectorAll('.bpop')].some(e=>e.textContent==='5')); await E(()=>{ if(BT) endBattle(); }); await W(100); return ok && await E(()=>document.querySelectorAll('.bpop').length===0); })());
  T('攻撃の 種類ごとに 当たった 見た目が 違う', await E(()=>{ const k=['w_elt','w_dolgan','tsuyogiri','volt','hono','raigeki','kabutowari','daimajin','e_hit','heal']; return k.every(x=>FXS_DEF[x]) && new Set(k.map(x=>JSON.stringify(FXS_DEF[x]))).size===k.length; }));
  T('呪文に すべて 解説が ある', await E(()=>Object.values(SKILLS).every(k=>k.desc&&k.desc.length>5)));
  T('呪文の 一覧で 解説が 出る', await E(()=>{ if(BT) endBattle(); if(msgQ) closeMsg(); openSpells('elt'); const ok=!!document.querySelector('#fmenu .mdesc'); closeMenu(); return ok; }));
  T('戦闘中に 魔物の 名前が 出る', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); startBattle([FOES.nousagi,FOES.nousagi]); }); await W(1500); const t=await E(()=>{ const el=document.getElementById('bfoes'); return el.style.display==='block' ? el.textContent : ''; }); await E(()=>{ if(BT) endBattle(); }); return /野ウサギA/.test(t) && /野ウサギB/.test(t); })());
  T('ドルムは 鉱山の 町の 並び（ルーエと 別）で、家に 入れる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_dolm'; enterTown([11.5,18.2],'velna'); }); await W(400); const ok1=await E(()=>cur.rows===DOLM && DOLM!==TOWN && DOLM.join('').includes('M') && DOLM.join('').includes('K'));
    await E(()=>{ if(msgQ) closeMsg(); hero.x=19.5; hero.z=10.9; hero.ang=Math.PI; resetTrail(); }); await pg.keyboard.down('ArrowUp'); await W(500); await pg.keyboard.up('ArrowUp'); await W(1500); const ok2=await E(()=>cur.kind==='room' && TROOMS()[cur.room].name==='鍛冶屋');
    await E(()=>{ busyDoor=0; enterTown([11.5,18.2],'velna'); }); await W(300); return ok1&&ok2; })());
  T('鍛冶屋で いまの 装備が 出る', await E(()=>{ if(BT) endBattle(); if(msgQ) closeMsg(); openShop('smith','鍛冶屋'); const el=document.getElementById('fequip'); const ok=el.style.display==='block' && el.textContent.includes(EQUIP.elt.weapon.name); closeMenu(); return ok && el.style.display==='none'; }));
  T('メニューの 字が 2段に ならない', await E(()=>{ const tests=[()=>openFieldMenu(),()=>openSound(),()=>openTactics(),()=>openShop('smith','鍛冶屋'),()=>{ openShop('smith','鍛冶屋'); MENU.onPick(0); },()=>openItems()]; let ok=true;
    tests.forEach(f=>{ if(msgQ) closeMsg(); f(); [...document.querySelectorAll('#fmenu > div:not(.mt):not(.mdesc)')].forEach(d=>{ const lh=parseFloat(getComputedStyle(d).lineHeight)||20; if(d.getBoundingClientRect().height>lh*1.5) ok=false; }); closeMenu(); }); return ok; }));
  T('塔から 王女に 話す 前は 出られない', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_tower'; enterTower(); }); await W(300); await pg.keyboard.down('ArrowDown'); await W(900); await pg.keyboard.up('ArrowDown'); await W(600); const ok=await E(()=>cur.kind==='tower'); await flush(); return ok; })());
  T('倉の あとに 畑で 全滅しても 襲撃が 始まる', await (async()=>{ await flush(); await E(()=>{ ST.phase='raid'; enterFarm(); startBattle([FOES.nousagi]); }); await W(800); await E(()=>{ wipeOut(); }); await W(1500); await flush(); await W(400); await flush(); return await E(()=>ST.phase==='burn' && TOWN_NOW==='rue'); })());
  T('エスケイルは 峠と 遺跡でも 入口へ', await E(()=>{ ST.phase='c2_pass'; enterDun('pass',true); const a=escapeTo(); enterDun('ruins'); const b=escapeTo(); enterFort(true); const c=escapeTo(); enterFort(false); const d=escapeTo(); return a[0]===64.6 && b[0]===74.5 && c[0]===41.6 && d[0]===37.5; }));
  T('第2章の ルーエは 焼け跡', await E(()=>{ ST.phase='c2_road'; enterTown([12,6],'rue'); return RUE_BURNT() && /焼け跡/.test(document.getElementById('place').textContent); }));
  T('章の 終わりの 札の 間は メニューが 開かない', await E(()=>{ const p=ST.phase; ST.phase='c1_end'; openFieldMenu(); const ok=!MENU; ST.phase=p; return ok; }));
  T('最初の 装備と ガイルの 剣は 外しても 付け直せる', await E(()=>{ fixGear(); const w=EQUIP.elt.weapon; return !!w.kind && canWear('elt',w); }));
  T('倒れた 仲間は 薬草で 起きない', await E(()=>{ const m={name:'t',hp:0,max:10}; const n=BAG.herbs=3; useHerb(m); return m.hp===0 && BAG.herbs===3; }));
  T('戦闘の 道具で 使う 相手を 選べる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_road'; if(!PARTY.includes('lidia')) joinParty('lidia',12); BAG.herbs=2; STATS.lidia.hp=5; startBattle([FOES.nousagi]); }); await W(1500); await E(()=>{ BT.phase='menu'; BT.sel=3; battleCmd(); }); const ph=await E(()=>BT.phase); await E(()=>{ itemPick(); BT.asel=BT.party.indexOf(STATS.lidia); allyPick(); }); await W(400); const ok=await E(()=>STATS.lidia.hp>5); await E(()=>{ if(BT) endBattle(); }); return ph==='item' && ok; })());
  T('ほかの 町に ルーエの 宝箱が ない', await E(()=>{ enterTown([11.5,15.5],'velna'); return !(CHESTS[chestKey()]||[]).length; }));
  T('町ごとに 鍛冶屋の 品が 違う', await E(()=>SHOP.smith_rue[0].name!==SHOP.smith_cap[0].name && SHOP.smith_cap[0].v>12 && SHOP.smith_velna[0].v>SHOP.smith_cap[0].v && SHOP.smith2[0].v>SHOP.smith_velna[0].v));
  T('ぼうぎょは 本人だけ', await E(()=>{ const src=foeAct.toString(); return /t\.guard/.test(src) && !/if\(BT\.guard\)/.test(src); }));
  T('仲間の 装備を 替えられる', await E(()=>{ BAG.gear.push({name:'魔導士の 杖',kind:'weapon',v:10,price:320}); openEquipOf('lidia'); MENU.onPick(0); const ok=MENU.items.some(t=>/魔導士の 杖/.test(t)); closeMenu(); return ok; }));
  T('音の 設定が 残る', await E(()=>{ SND.bgm=.3; openSound(); closeMenu(); return JSON.parse(localStorage.getItem('lq5snd')).bgm===.3; }));
  T('王都の 南の 家から 出ても 壁に 入らない', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c1_road'; TOWN_NOW='cap'; lastDoor=4; enterRoom(4); hero.x=4.5; hero.z=5.3; resetTrail(); busyDoor=0; }); await pg.keyboard.down('ArrowDown'); await W(1200); await pg.keyboard.up('ArrowDown'); await W(1200);
    await pg.keyboard.down('ArrowDown'); await W(1000); await pg.keyboard.up('ArrowDown'); await W(200); return await E(()=>cur.kind==='town' && hero.z<21 && freeCircle(hero.x,hero.z)); })());
  T('場所を 移っても 形が 増え続けない', await E(()=>{ for(let i=0;i<3;i++){ enterTown([11.5,15.5],'velna'); enterTown([12,10],'cap'); } const g0=R.info.memory.geometries; for(let i=0;i<10;i++){ enterTown([11.5,15.5],'velna'); enterTown([12,10],'cap'); } return R.info.memory.geometries-g0 < 60; }));
  T('畑の 入口は 木と 重ならない', await E(()=>{ ST.phase='field'; enterFarm(); return freeCircle(hero.x,hero.z) && freeCircle(12,13.5); }));
  T('戦闘の 道具の 文が 崩れない', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_road'; if(!PARTY.includes('lidia')) joinParty('lidia',12); BAG.herbs=2; STATS.lidia.hp=STATS.lidia.max; startBattle([FOES.nousagi]); }); await W(1500); await E(()=>{ BT.phase='menu'; BT.sel=3; battleCmd(); itemPick(); BT.asel=BT.party.indexOf(STATS.lidia); allyPick(); }); await W(150); const t=await E(()=>bmsg.textContent); await E(()=>{ if(BT) endBattle(); }); return !/に リディアの/.test(t) && /減って いない/.test(t); })());
  T('試作の 文が 残って いない', await E(()=>!document.documentElement.innerHTML.includes('試作：')));
  T('帝都の 鍛冶屋でも いまの 装備が 出る', await E(()=>{ if(BT) endBattle(); if(msgQ) closeMsg(); openShop('smith2','店'); const ok=document.getElementById('fequip').style.display==='block'; closeMenu(); return ok; }));
  T('ぼうぎょは 戦闘の 後に 残らない', await E(()=>{ STATS.elt.guard=true; startBattle([FOES.nousagi]); const a=STATS.elt.guard; endBattle(); return a===false && STATS.elt.guard===false; }));
  T('店主に カウンター越しに 話せる', await (async()=>{ await flush(); await E(()=>{ ST.phase='c1_road'; TOWN_NOW='cap'; enterRoom(1); hero.x=4.5; hero.z=4.39; hero.ang=Math.PI; resetTrail(); }); await W(300); await E(()=>pressA()); await W(200); const t=await E(()=>document.getElementById('msg').textContent+(msgQ?JSON.stringify(msgQ):'')); await flush(); await E(()=>{ if(MENU) closeMenu(); }); return /薬草|道具/.test(t); })());
  T('帝都は 王都と 別の 並びで、家と 城に 入れる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_inn'; enterTown([12,20.2],'vcap'); }); await W(300); const ok1=await E(()=>cur.rows===VCAP && VCAP!==CAP && VCAP.join('').includes('Y') && VCAP.join('').includes('S'));
    await E(()=>{ if(msgQ) closeMsg(); hero.x=5.5; hero.z=19.9; hero.ang=Math.PI; resetTrail(); busyDoor=0; }); await pg.keyboard.down('ArrowUp'); await W(500); await pg.keyboard.up('ArrowUp'); await W(1500); const ok2=await E(()=>cur.kind==='room' && TROOMS()[cur.room].name==='教会');
    await E(()=>{ busyDoor=0; enterTown([12,5.5],'vcap'); if(msgQ) closeMsg(); }); await pg.keyboard.down('ArrowUp'); await W(900); await pg.keyboard.up('ArrowUp'); await W(1500); const ok3=await E(()=>cur.kind==='castle');
    await flush(); return ok1&&ok2&&ok3; })());
  T('帝都の 城は アルディア城と 別の 並びで、王・侍女が いる', await E(()=>{ if(BT) endBattle(); ST.phase='c2_inn'; enterCastle('velna'); const ok=cur.rows===VCASTLE && VCASTLE!==CASTLE && cur.npcs.some(n=>n.name==='侍女') && cur.npcs.some(n=>n.name==='ヴェルナ王') && cur.npcs.every(n=>!cur.solid.has(cur.rows[Math.floor(n.y)][Math.floor(n.x)])); enterCastle(); const ok2=cur.rows===CASTLE; return ok&&ok2; }));
  T('外の 地図の 帝都は 専用の 絵', await E(()=>!!WOBJ_IMG.vcastle));
  T('経験値は 1.25倍', await E(()=>EXP_RATE===1.25));
  T('扉の 出入りが 暗転と 重なっても 動けなく ならない', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c1_road'; enterTown([12,10],'cap'); window.__ran=0; fading=1; goDoor(()=>{ window.__ran=1; }); setTimeout(()=>{ fading=0; },300); busyDoor=1; }); await W(3200); return await E(()=>window.__ran===1 && busyDoor===0); })());
  T('教会の 長いすの 横から 下を 押すと 出られる', await (async()=>{ await flush(); await E(()=>{ ST.phase='c1_road'; TOWN_NOW='cap'; lastDoor=2; enterRoom(2); hero.x=3.5; hero.z=2.6; resetTrail(); busyDoor=0; }); await W(400); await pg.keyboard.down('ArrowDown'); await W(3000); await pg.keyboard.up('ArrowDown'); await W(1200); return await E(()=>cur.kind==='town'); })());
  T('鍛冶屋に 話しかけた ときから いまの 装備が 出る', await (async()=>{ await flush(); await E(()=>{ ST.phase='c2_road'; TOWN_NOW='velna'; lastDoor=2; enterRoom(2); const n=cur.npcs[0]; n.talk(n); }); await W(200); const ok=await E(()=>document.getElementById('fequip').style.display==='block' && !!msgQ); await flush(); await E(()=>{ if(MENU) closeMenu(); }); return ok; })());
  T('峠の 山道は 広く、関所荒らしを 倒すまで 抜けられない', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_pass'; enterDun('pass'); hero.x=48.3; hero.z=8.6; resetTrail(); }); await W(200); await pg.keyboard.down('ArrowRight'); await W(600); await pg.keyboard.up('ArrowRight'); await W(400); const ok=await E(()=>DUNS.pass.rows[0].length===50 && cur.kind!=='world' && ST.phase==='c2_pass'); await E(()=>{ if(BT) endBattle(); }); await flush(); return ok; })());
  T('外の 地図に 峠の 印（閉じた 関所 → 開いた 関所）', await E(()=>{ ST.phase='c2_dolm'; applyWorldState(); const a=WORLD[25][62]==='Q'; ST.phase='c2_pass'; applyWorldState(); return a && WORLD[25][62]==='G' && !!WOBJ_IMG.pass_open && !!WOBJ_IMG.pass_closed; }));
  T('地図は 拡大で 開き、十字で 動き、Aで 全体', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_road'; enterWorld([48.5,26.5]); if(msgQ) closeMsg(); openMap(); }); await W(200); const a=await E(()=>mapOpen && mapSt.zoom===1 && mapSt.cx); await pg.keyboard.down('ArrowRight'); await W(500); await pg.keyboard.up('ArrowRight'); const b2=await E(()=>[mapSt.cx, hero.x]); await E(()=>pressA()); const z=await E(()=>mapSt.zoom); await E(()=>pressB()); await W(100); await E(()=>{ if(MENU) closeMenu(); }); return b2[0]>a+1 && Math.abs(b2[1]-48.5)<.01 && z===0; })());
  T('地図には 行った 場所だけ 名前が 出る', await E(()=>{ const v=ST.visited; ST.visited={rue:1}; const p=ST.phase; ST.phase='morning'; const a=MAP_NAMES.filter(m=>{ visitedFromPhase(); return ST.visited[m[3]]; }).length; ST.phase='c1_town'; visitedFromPhase(); const b2=MAP_NAMES.filter(m=>ST.visited[m[3]]).length; ST.phase=p; ST.visited=Object.assign(v||{},ST.visited); return a===1 && b2===4; }));
  T('帝都の 宿で 寝ると 侍女が 部屋に 入って くる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_inn'; BAG.gold=100; TOWN_NOW='vcap'; lastDoor=3; enterRoom(3); if(MENU) closeMenu(); openInn(); MENU.onPick(0); }); await W(1500); for(let i=0;i<4;i++){ await E(()=>{ if(msgQ) pressA(); }); await W(150); } for(let i=0;i<40 && !(await E(()=>/侍女/.test(document.getElementById('msg').textContent)));i++) await W(200);
    const ok=await E(()=>cur.kind==='room' && cur.npcs.some(n=>n.name==='侍女') && /侍女/.test(document.getElementById('msg').textContent)); for(let i=0;i<6;i++){ await E(()=>{ if(msgQ) pressA(); }); await W(150); } await W(1200); return ok && await E(()=>ST.phase==='c2_tower' && cur.kind==='tower'); })());
  T('リディアが 仲間に なると 1人だけ 見え、動くと ついて くる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); const i=PARTY.indexOf('lidia'); if(i>0) PARTY.splice(i,1); refreshFollowers(); ST.phase='c2_tower'; enterTower(); const n=cur.npcs.find(n=>n.spr==='lidia'); n.talk(n); }); for(let i=0;i<30;i++){ const t=await E(()=>document.getElementById('msg').textContent); if(/抜け出した/.test(t)) break; await E(()=>pressA()); await W(60); }
    const one=await E(()=>cur.npcs.filter(n=>n.spr==='lidia').length===0 && followers.filter(f=>f.p.k==='lidia').length===1 && followers.find(f=>f.p.k==='lidia').hold===true); await flush(); await W(800); return one; })());
  T('ボスの 名前は 魔導からくり ZF、戦闘前に 胸の ZF', await E(()=>FOES.zfboss.name==='魔導からくり ZF' && zfFight.toString().includes('胸を 見ると「ZF」')));
  T('作戦「めいれい させろ」で 仲間を 1人ずつ 操作できる', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); tactic='manual'; ['lidia','zf'].forEach(k=>{ if(!PARTY.includes(k)) joinParty(k,12); }); startBattle([FOES.nousagi]); }); for(let i=0;i<40 && !(await E(()=>BT&&BT.phase==='menu'));i++) await W(100);
    const a=await E(()=>{ const r=[]; BT.sel=0; pressA(); r.push(BT.cur); BT.sel=2; pressA(); r.push(BT.cur); pressB(); r.push(BT.cur); BT.sel=2; pressA(); BT.sel=2; pressA(); r.push(BT.phase); return r.join(','); }); await W(300); await E(()=>{ if(BT) endBattle(); }); return a==='1,2,1,act'; })());
  T('鍛冶屋で 買った 装備を その場で 付けられる・装備の 画面に ＋', await E(()=>{ if(BT) endBattle(); if(msgQ) closeMsg(); BAG.gold=999; const w0=EQUIP.elt.weapon; const g={name:'試しの 剣',kind:'weapon',v:30,price:10}; BAG.gear.push(g); askWear(g,()=>{}); MENU.onPick(0); while(msgQ) closeMsg(); const ok=EQUIP.elt.weapon===g && BAG.gear.includes(w0); if(MENU) closeMenu(); openEquipOf('elt'); const ok2=/（\+30）/.test(MENU.items[0]); closeMenu(); EQUIP.elt.weapon=w0; BAG.gear=BAG.gear.filter(x=>x!==w0); syncAtk(); return ok&&ok2; }));
  T('ドルムの 教会で セーブ → 再開も ドルムの 教会', await (async()=>{ await flush(); await E(()=>{ if(BT) endBattle(); ST.phase='c2_dolm'; enterTown([11.5,15.5],'velna'); lastDoor=3; enterRoom(3); hero.x=4.5; hero.z=4.5; saveGame(); enterTown([12,6],'rue'); }); await pg.reload({waitUntil:'load'}); await W(1800);
    for(let i=0;i<40 && !(await E(()=>typeof MENU!=='undefined'));i++) await W(100); await W(600); await E(()=>{ if(MENU) closeMenu(); loadGame(); }); await W(800);
    return await E(()=>TOWN_NOW==='velna' && cur.kind==='room' && TROOMS()[cur.room].name==='教会'); })());
  T('ブラウザの エラー なし', errs.length===0, errs.join(' / '));
  console.log('--- lq5 test: '+(n-ng)+'/'+n+' 通過 ---'); await b.close(); process.exit(ng?1:0);
})().catch(e=>{ console.log('NG 実行',e.message); process.exit(1); });
